1=Computer University, Pathein
2=Computer University, Maubin
3=Computer University, Hinthada
4=Technological University, Pathein
5=Technological University, Maubin
6=Technological University, Hinthada
7=Other
