1=Computer University,Mandalay
2=Computer University,Meiktila
3=Mandalay Technological University
4=Technological University, Mandalay
5=Technological University, Meikhtila
6=Technological University, Kyaukse
7=University of Computer Studies, Mandalay
8=University of Foreign Languages, Mandalay
9=University of Medicine, Mandalay
10=University of Technology, Yatanarpon Cyber City
11=Other

