1=Computer University, Lashio
2=Computer University, Kyaingtong
3=Computer University, Panglong
4=Computer University, Taunggyi
5=Technological University, Kyaingtong
6=Technological University, Lashio
7=Technological University, Panglong
8=Technological University, Taunggyi
9=University of Medicine, Taunggyi
10=Other



