1=Yangon University
2=University of Computer Studies
3=University of Foreign Languages
4=University of Medicine 1
5=University of Medicine 2
6=Dagon University
7=West Yangon Technological University
8=Technological University, Hmawbi
9=Technological University,Thanlyin
10=University of East Yangon
11=University of West Yangon
12=University of Information Technology, Yangon
13=Other

